### ISSUE TITLE
How to find the prior images of the current image？

### ISSUE THREAD

**Issue by Liqq1** [aehrc/cxrmate#1]
Hi! Thanks for your contribution. It is an excellent piece of work!

I would like to know how the prior images of the current image are identified in this paper.
Upon careful examination of the MIMIC-CXR-v2 dataset, I have observed that its documentation states, _"These study identifiers are completely random, and their order has no implications for the chronological order of the actual studies. "_ Additionally, the time information in the reports is masked (e.g., "In comparison with the study of ___"). Therefore, I am uncertain about how to identify the prior images corresponding to a given current image. 

Thank you very much for your time and consideration. I eagerly look forward to your response.

**Comment by yihp** [comment]
Hi!
I have the same question, do you know the answer now?
