### ISSUE TITLE
Multi-card training problem

### ISSUE THREAD

**Issue by yihp** [aehrc/cxrmate#7]
Hi！
when i run “dlhpcstarter -t cxrmate -c config/train/longitudinal_gt_prompt_tf.yaml --stages_module tools.stages --train”
But the speed is very slow. How should I set the training parameters and data batches to speed up the training process?
Only 4013MiB / 32768MiB of memory is used single gup
and my gpu card is 32G*2
Thank you very much!

**Comment by anicolson** [comment]
Hi,

You can up the mini-batch size? Is your dataset on a solid state drive, or a disk? What is your iterations per second?

**Comment by yihp** [comment]
> Hi,
> 
> You can up the mini-batch size? Is your dataset on a solid state drive, or on a hard disk? What is your iterations per second?

my mbatch_size is set 2，my dataset on a hard disk，2.77iterations per second
![image](https://github.com/aehrc/cxrmate/assets/130024120/ba24d2cc-fcc1-4fb1-893b-299096a6cac9)
![image](https://github.com/aehrc/cxrmate/assets/130024120/40491ca6-a4ed-43d6-bc91-ba7df42ca785)

my gpu is v100*2

**Comment by anicolson** [comment]
I get a pretty big speedup from using a solid state drive over a hard disk. A mini-batch size of up to 32 should be fine (so devices: 2 and mbatch_size: 16, which is a mini-batch size of 32 with ddp). You can also increase the number of workers for the dataloader (I think i have it already set high enough though with num_workers: 5 in the config).

I will have to dig up my number of iterations per second tomorrow when I am at my computer. Bare in mind this paper was done on P100 gpus, so it will be slower.

**Comment by anicolson** [comment]
Also, I found the CvT encoder to be quite slow, if you see our later work, e.g, 

https://huggingface.co/aehrc/cxrmate-ed


https://github.com/aehrc/anon

we use UniFormer which has sped up training quite a bit.

**Comment by yihp** [comment]
Yes, I saw this work, it is great, adding Auxiliary Patient Data. But I currently want to test multi-image input and Longitudinal Data. and I think I should read it carefully.

**Comment by yihp** [comment]
hi
I want to ask you how many epochs did you train with teacher forcing and train with Self-Critical Sequence Training (SCST) respectively?

**Comment by yihp** [comment]
> hi
> I want to ask you how many epochs did you train with teacher forcing and train with Self-Critical Sequence Training (SCST) respectively?

@anicolson hi, Are max_epochs set to 32 and 1 respectively? I saw this in the training configuration, but I don't know if it's accurate.

**Comment by yihp** [comment]
> > hi
> > I want to ask you how many epochs did you train with teacher forcing and train with Self-Critical Sequence Training (SCST) respectively?
> 
> @anicolson hi, Are max_epochs set to 32 and 1 respectively? I saw this in the training configuration, but I don't know if it's accurate.

Oh, I just saw the training parameters in the paper, thank you
